language: php
sudo: required
php:
    - "5.6      "
os: linux
dist: trusty
service: mysql
         
before_script:
- composer update
- cp travis/env .env
- ./artisan key:generate
- mysql -e "create database hikeroute"
- ./artisan -vvv --force --step --no-interaction migrate 
- ./artisan -vvv --force --step --no-interaction migrate:refresh
- ./artisan makeadmin admin admin@example.com >pass
- mysql --database=hikeroute -e "desc routefiles"
