language: php
sudo: required
php:
        - '5.6'
matrix:
        include:        
        -os: linux
         dist: trusty
         service: mysql
         
before_script:
-sudo apt-get install curl git
-curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
-composer update
