language: php
sudo: required
php:
        - '5.6'

os: linux
dist: trusty
service: mysql
         
before_script:
- sudo apt-get install -y php-mbstring php-PDO
- composer update
- cp travis/env .env
- ./artisan key:generate
- mysql -e "create database hikeroute"
- tail .env
- ./artisan migrate --no-interaction
