language: php
sudo: required
php:
    - "5.6      "
os: linux
dist: trusty
service: mysql
         
before_script:
- composer update
- cp travis/env .env
- ./artisan key:generate
- mysql -e "create database hikeroute"
- ./artisan migrate --no-interaction
- ./artisan makeadmin testadmin admin@example.com >pass

