language: php
sudo: required
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            -mbstring
            -PDO

os: linux
dist: trusty
service: mysql
         
before_script:
- composer update
- cp travis/env .env
- ./artisan key:generate
- mysql -e "create database hikeroute"
- tail .env
- ./artisan migrate --no-interaction
